# Generated by Django 4.1.7 on 2023-11-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_one_title', models.CharField(max_length=100)),
                ('section_one_description', models.TextField()),
                ('section_one_image_one', models.ImageField(upload_to='home_page_images/')),
                ('section_one_image_two', models.ImageField(upload_to='home_page_images/')),
            ],
        ),
    ]
