# Generated by Django 4.1.7 on 2023-11-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPageModel',
        ),
    ]
