# Generated by Django 4.1.7 on 2023-11-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0002_delete_aboutpagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_description', models.TextField()),
                ('about_image_one', models.ImageField(upload_to='about_page_images/')),
                ('about_image_two', models.ImageField(upload_to='about_page_images/')),
            ],
        ),
    ]
