# Generated by Django 4.1.7 on 2023-11-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_aboutpagemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagemodel',
            options={'verbose_name_plural': 'About page'},
        ),
    ]
