# Generated by Django 4.1.7 on 2023-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_aboutpagemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagemodel',
            name='about_slug_one',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='aboutpagemodel',
            name='about_slug_two',
            field=models.SlugField(default=''),
        ),
    ]
