# Generated by Django 4.1.7 on 2023-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_aboutpagemodel_about_slug_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagemodel',
            name='about_slug_one',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutpagemodel',
            name='about_slug_two',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
