# Generated by Django 4.1.7 on 2023-11-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_aboutpagemodel_about_slug_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image_one', models.ImageField(upload_to='service_page_images/')),
                ('service_slug_one', models.SlugField(blank=True, default='')),
                ('service_title_one', models.CharField(max_length=255)),
                ('service_list_one', models.TextField()),
                ('service_image_two', models.ImageField(upload_to='service_page_images/')),
                ('service_slug_two', models.SlugField(blank=True, default='')),
                ('service_title_two', models.CharField(max_length=255)),
                ('service_list_two', models.TextField()),
                ('service_image_three', models.ImageField(upload_to='service_page_images/')),
                ('service_slug_three', models.SlugField(blank=True, default='')),
                ('service_title_three', models.CharField(max_length=255)),
                ('service_list_three', models.TextField()),
                ('service_image_four', models.ImageField(upload_to='service_page_images/')),
                ('service_slug_four', models.SlugField(blank=True, default='')),
                ('service_title_four', models.CharField(max_length=255)),
                ('service_list_four', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Service page',
            },
        ),
    ]
