# Generated by Django 4.1.7 on 2023-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_servicepagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaching_title', models.CharField(max_length=100)),
                ('coaching_description', models.TextField()),
                ('coaching_image_one', models.ImageField(upload_to='about_page_images/')),
                ('coaching_slug_one', models.SlugField(blank=True, default='')),
                ('coaching_image_two', models.ImageField(upload_to='about_page_images/')),
                ('coaching_slug_two', models.SlugField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Coaching page',
            },
        ),
    ]
