# Generated by Django 4.1.7 on 2023-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_servicepagemodel_service_image_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepagemodel',
            name='service_image_four',
            field=models.ImageField(null=True, upload_to='service_page_images/'),
        ),
        migrations.AlterField(
            model_name='servicepagemodel',
            name='service_image_one',
            field=models.ImageField(null=True, upload_to='service_page_images/'),
        ),
        migrations.AlterField(
            model_name='servicepagemodel',
            name='service_image_three',
            field=models.ImageField(null=True, upload_to='service_page_images/'),
        ),
        migrations.AlterField(
            model_name='servicepagemodel',
            name='service_image_two',
            field=models.ImageField(null=True, upload_to='service_page_images/'),
        ),
    ]
