# Generated by Django 4.1.7 on 2023-11-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_servicepagemodel_service_image_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagemodel',
            name='about_image_one',
            field=models.ImageField(null=True, upload_to='about_page_images/'),
        ),
        migrations.AlterField(
            model_name='aboutpagemodel',
            name='about_image_two',
            field=models.ImageField(null=True, upload_to='about_page_images/'),
        ),
    ]
