# Generated by Django 4.1.7 on 2023-12-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_rename_clientinformationmodel_clientinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientinformation',
            options={'verbose_name': 'Client information'},
        ),
    ]
