# Generated by Django 4.1.7 on 2023-12-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_clientinformation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientinformation',
            options={'verbose_name_plural': 'Client information'},
        ),
    ]
