# Generated by Django 4.1.7 on 2023-12-08 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_clientinformation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
