# Generated by Django 4.1.7 on 2023-12-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_clientinformation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('strategy', models.CharField(max_length=1000)),
                ('stat_one', models.CharField(max_length=10)),
                ('text_one', models.CharField(max_length=25)),
                ('stat_two', models.CharField(max_length=10)),
                ('text_two', models.CharField(max_length=25)),
                ('stat_three', models.CharField(max_length=10)),
                ('text_three', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectVideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='projects_videos/')),
                ('test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='project_videos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.projectmodel')),
            ],
        ),
    ]
