# Generated by Django 4.1.7 on 2023-12-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_projectmodel_projectvideosmodel_projectvideomodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectvideosmodel',
            old_name='test_info',
            new_name='project',
        ),
        migrations.DeleteModel(
            name='ProjectVideoModel',
        ),
    ]
