# Generated by Django 4.1.7 on 2023-12-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_rename_test_info_projectvideosmodel_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(default='Project', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='strategy',
            field=models.TextField(max_length=1000),
        ),
    ]
