# Generated by Django 4.1.7 on 2023-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_projectmodel_name_alter_projectmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimagesmodel',
            name='image_slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectimagesmodel',
            name='name',
            field=models.CharField(default='Project photo', max_length=100),
        ),
        migrations.AddField(
            model_name='projectvideosmodel',
            name='name',
            field=models.CharField(default='Project video', max_length=100),
        ),
    ]
