# Generated by Django 4.1.7 on 2023-12-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_projectimagesmodel_image_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimagesmodel',
            options={'verbose_name_plural': 'Project images'},
        ),
        migrations.AlterModelOptions(
            name='projectvideosmodel',
            options={'verbose_name_plural': 'Project videos'},
        ),
    ]
