# Generated by Django 4.1.7 on 2023-12-16 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_projectimagesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project_covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='review',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
