# Generated by Django 4.1.7 on 2023-12-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_projectmodel_cover_projectmodel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='cover',
            field=models.ImageField(null=True, upload_to='project_covers/'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
