# Generated by Django 4.1.7 on 2023-12-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_projectmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMediaStatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project media statistics', max_length=100)),
                ('image', models.ImageField(upload_to='projects_media_stat/')),
                ('image_slug', models.SlugField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.projectmodel')),
            ],
            options={
                'verbose_name_plural': 'Project media stat',
            },
        ),
    ]
