# Generated by Django 4.1.7 on 2023-12-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_projectmediastatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='media_stat_content_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='photo_content_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='video_content_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectimagesmodel',
            name='name',
            field=models.CharField(default='Project photo', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmediastatmodel',
            name='name',
            field=models.CharField(default='Project media statistics', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectvideosmodel',
            name='name',
            field=models.CharField(default='Project video', max_length=200),
        ),
    ]
