# Generated by Django 4.1.7 on 2024-03-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_projectmodel_media_stat_content_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='is_home_page',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
