# Generated by Django 4.1.7 on 2024-03-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_clientinformation_is_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinformation',
            name='is_home_page',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='is_home_page',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
