# Generated by Django 4.1.7 on 2024-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_remove_clientinformation_is_home_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='is_ugc',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
